<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.WAllergiesTest" tests="9" failures="1" timestamp="16 Jul 2018 20:14:12 GMT" time="486.595" errors="0">
  <testcase name="AllergySelectionTest" time="70.282" classname="com_Milan_Test.WAllergiesTest"/>
  <testcase name="FoodAllergyvalidationTest" time="53.400" classname="com_Milan_Test.WAllergiesTest"/>
  <testcase name="AddNewAllergiesTest" time="50.491" classname="com_Milan_Test.WAllergiesTest"/>
  <testcase name="AllergiesOnDashboardforNewPatientTest" time="52.773" classname="com_Milan_Test.WAllergiesTest"/>
  <testcase name="OptionSelectedOnAllergyCurrentStstusTest" time="51.193" classname="com_Milan_Test.WAllergiesTest">
    <failure type="java.lang.AssertionError" message="expected [Present] but found []">
      <![CDATA[java.lang.AssertionError: expected [Present] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAllergiesTest.OptionSelectedOnAllergyCurrentStstusTest(WAllergiesTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- OptionSelectedOnAllergyCurrentStstusTest -->
  <testcase name="OptionSelectedOnAllergyCurrentStstusTest" time="49.531" classname="com_Milan_Test.WAllergiesTest">
    <skipped/>
  </testcase> <!-- OptionSelectedOnAllergyCurrentStstusTest -->
  <testcase name="OptionSelectedOnAllergyCurrentStstusTest" time="53.516" classname="com_Milan_Test.WAllergiesTest">
    <skipped/>
  </testcase> <!-- OptionSelectedOnAllergyCurrentStstusTest -->
  <testcase name="OptionSelectedOnAllergyCurrentStstusTest" time="52.282" classname="com_Milan_Test.WAllergiesTest">
    <skipped/>
  </testcase> <!-- OptionSelectedOnAllergyCurrentStstusTest -->
  <testcase name="ExistingPatientDrugAllergyTypeTest" time="53.127" classname="com_Milan_Test.WAllergiesTest"/>
</testsuite> <!-- com_Milan_Test.WAllergiesTest -->
